import { ReactNode, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Shield, LogOut, Menu } from "lucide-react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { adminNavigation, getAdminNavItem } from "@/lib/admin/navigation";
interface AdminLayoutProps { children: ReactNode; activeTab?: string; onTabChange?: (tab: string) => void; }
export function AdminLayout({ children, activeTab }: AdminLayoutProps) {
    const router = useRouter(); const [loading, setLoading] = useState(true); const [isSuperAdmin, setIsSuperAdmin] = useState(false);
    useEffect(() => { checkSuperAdmin(); }, []);
    const checkSuperAdmin = async () => { try { const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.push("/login"); return; } const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single(); if (profile?.role !== "super_admin") { router.push("/dashboard"); return; } setIsSuperAdmin(true); } catch (error) { console.error("Error checking super admin:", error); router.push("/dashboard"); } finally { setLoading(false); } };
    const handleSignOut = async () => { await supabase.auth.signOut(); router.push("/login"); };
    const currentHref = useMemo(() => { if (activeTab) { const legacyMap: Record<string, string> = { dashboard: "/admin/dashboard", control: "/admin/dashboard", revenue: "/admin/billing", companies: "/admin/companies", users: "/admin/companies", notifications: "/admin/communications", messaging: "/admin/communications", leads: "/admin/support", plans: "/admin/plans", addons: "/admin/addons", roles: "/admin/security", audit: "/admin/audit", reports: "/admin/dashboard", settings: "/admin/settings" }; return legacyMap[activeTab] || "/admin/dashboard"; } return getAdminNavItem(router.pathname)?.href || "/admin/dashboard"; }, [activeTab, router.pathname]);
    const renderNav = () => <nav className="space-y-1">{adminNavigation.map((item) => { const isActive = currentHref === item.href || router.pathname === item.href; return <Link key={item.href} href={item.href}><Button variant={isActive ? "secondary" : "ghost"} className="w-full justify-start"><item.icon className="mr-2 h-4 w-4" />{item.name}</Button></Link>; })}</nav>;
    if (loading) return <div className="min-h-screen flex items-center justify-center"><div className="text-center"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div><p className="text-muted-foreground">Loading...</p></div></div>;
    if (!isSuperAdmin) return null;
    return <div className="min-h-screen bg-background"><div className="lg:hidden border-b bg-card px-4 py-3 flex items-center justify-between"><div className="flex items-center gap-2"><Shield className="h-6 w-6 text-primary" /><span className="font-bold text-lg">Super Admin</span></div><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon"><Menu className="h-5 w-5" /></Button></SheetTrigger><SheetContent side="left" className="w-72 p-0"><div className="p-6"><div className="flex items-center gap-2 mb-6"><Shield className="h-6 w-6 text-primary" /><span className="font-bold text-lg">Super Admin</span></div>{renderNav()}</div></SheetContent></Sheet></div><div className="hidden lg:fixed lg:inset-y-0 lg:flex lg:w-72 lg:flex-col"><div className="flex flex-col flex-1 min-h-0 border-r bg-card"><div className="flex items-center h-16 px-6 border-b"><Shield className="h-6 w-6 text-primary mr-2" /><span className="font-bold text-lg">Super Admin</span></div><div className="flex-1 flex flex-col overflow-y-auto"><div className="px-3 py-4">{renderNav()}</div><div className="p-3 border-t mt-auto"><Button variant="ghost" className="w-full justify-start" onClick={handleSignOut}><LogOut className="mr-2 h-4 w-4" />Sign Out</Button></div></div></div></div><div className="lg:pl-72"><main className="flex-1">{children}</main></div></div>
}
