ALTER TABLE inventory_items
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS quantity_on_hand INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS quantity_allocated INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS supplier_name TEXT;

ALTER TABLE job_types
ADD COLUMN IF NOT EXISTS category TEXT,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS estimated_hours NUMERIC,
ADD COLUMN IF NOT EXISTS estimated_cost NUMERIC;

ALTER TABLE suppliers
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS contact_person TEXT;